using AlxCousrseHomework.MailingService;
using AlxCousrseHomework.MaterialAssignments;
using AlxCousrseHomework.ShootingRange;

Console.WriteLine("Marcin Dziadzio");
Console.WriteLine("Prace domowe !");
//Console.WriteLine("..........................................................................");
//Console.WriteLine("Mailing Service");
//Console.WriteLine("..........................................................................");
//Console.WriteLine();
//Homework1Test.Run();
//Console.WriteLine("Koniec zadania Mailing Service ...........................................");
//Console.ReadLine();
//Console.WriteLine("Zadania z Rozdziałów");
//Console.WriteLine();
//Chapter01.Run();
//Console.ReadLine();
//Console.WriteLine();
//Chapter02.Run();
//Console.ReadLine();
//Console.WriteLine();
//Chapter03.Run();
//Console.ReadLine();
Console.WriteLine();
Console.WriteLine("Strzelnica");
Console.WriteLine("Naciśnij dowolny klawisz i rozpocznij zadanie ....");
Console.ReadLine();
Console.Clear();    
ShootingRange.Run();
//Console.ReadLine();

